version: '3'

services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_app
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data